-- Premium & Ambassador System Migration
-- Created: January 23, 2026

-- ============================================
-- 1. AMBASSADORS TABLE
-- ============================================
-- Tracks users with ambassador status who can generate referral codes

CREATE TABLE IF NOT EXISTS ambassadors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'revoked')),
    max_codes INTEGER NOT NULL DEFAULT 5,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes TEXT, -- Admin notes about why they're an ambassador
    UNIQUE(user_id)
);

-- Index for quick lookups
CREATE INDEX IF NOT EXISTS idx_ambassadors_user_id ON ambassadors(user_id);
CREATE INDEX IF NOT EXISTS idx_ambassadors_status ON ambassadors(status);

-- ============================================
-- 2. REFERRAL CODES TABLE
-- ============================================
-- Tracks referral codes generated by ambassadors

CREATE TABLE IF NOT EXISTS referral_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT NOT NULL UNIQUE,
    created_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    redeemed_by UUID REFERENCES users(id) ON DELETE SET NULL,
    premium_days INTEGER NOT NULL DEFAULT 7,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL, -- Code expiry (not premium expiry)
    redeemed_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'redeemed', 'expired', 'revoked'))
);

-- Indexes for lookups
CREATE INDEX IF NOT EXISTS idx_referral_codes_code ON referral_codes(code);
CREATE INDEX IF NOT EXISTS idx_referral_codes_created_by ON referral_codes(created_by);
CREATE INDEX IF NOT EXISTS idx_referral_codes_redeemed_by ON referral_codes(redeemed_by);
CREATE INDEX IF NOT EXISTS idx_referral_codes_status ON referral_codes(status);

-- ============================================
-- 3. PREMIUM TRANSACTIONS TABLE
-- ============================================
-- Tracks all premium activations for audit trail

CREATE TABLE IF NOT EXISTS premium_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    transaction_type TEXT NOT NULL CHECK (transaction_type IN ('referral', 'promo_code', 'purchase', 'ambassador_grant', 'admin_grant')),
    source_code TEXT, -- The referral/promo code used (if applicable)
    source_user_id UUID REFERENCES users(id), -- Who referred them (if applicable)
    premium_days INTEGER NOT NULL,
    activated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_premium_transactions_user_id ON premium_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_premium_transactions_source_user_id ON premium_transactions(source_user_id);

-- ============================================
-- 4. USER REFERRAL TRACKING
-- ============================================
-- Add column to track if user has ever used a referral code (one-time only)

ALTER TABLE users 
ADD COLUMN IF NOT EXISTS has_used_referral BOOLEAN DEFAULT FALSE;

ALTER TABLE users 
ADD COLUMN IF NOT EXISTS referred_by UUID REFERENCES users(id);

-- ============================================
-- 5. RPC: CHECK AMBASSADOR STATUS
-- ============================================

CREATE OR REPLACE FUNCTION check_ambassador_status(p_user_id UUID)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_ambassador ambassadors%ROWTYPE;
    v_active_codes INTEGER;
    v_total_redeemed INTEGER;
BEGIN
    -- Get ambassador record
    SELECT * INTO v_ambassador
    FROM ambassadors
    WHERE user_id = p_user_id AND status = 'active';
    
    IF NOT FOUND THEN
        RETURN json_build_object(
            'is_ambassador', false
        );
    END IF;
    
    -- Count active codes
    SELECT COUNT(*) INTO v_active_codes
    FROM referral_codes
    WHERE created_by = p_user_id 
    AND status = 'active'
    AND expires_at > NOW();
    
    -- Count total redeemed
    SELECT COUNT(*) INTO v_total_redeemed
    FROM referral_codes
    WHERE created_by = p_user_id AND status = 'redeemed';
    
    RETURN json_build_object(
        'is_ambassador', true,
        'max_codes', v_ambassador.max_codes,
        'active_codes', v_active_codes,
        'total_redeemed', v_total_redeemed,
        'can_generate_code', v_active_codes < v_ambassador.max_codes
    );
END;
$$;

-- ============================================
-- 6. RPC: GENERATE REFERRAL CODE
-- ============================================

CREATE OR REPLACE FUNCTION generate_referral_code(p_user_id UUID)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_ambassador ambassadors%ROWTYPE;
    v_active_codes INTEGER;
    v_new_code TEXT;
    v_code_record referral_codes%ROWTYPE;
BEGIN
    -- Check ambassador status
    SELECT * INTO v_ambassador
    FROM ambassadors
    WHERE user_id = p_user_id AND status = 'active';
    
    IF NOT FOUND THEN
        RETURN json_build_object(
            'success', false,
            'error', 'not_ambassador'
        );
    END IF;
    
    -- Count active codes
    SELECT COUNT(*) INTO v_active_codes
    FROM referral_codes
    WHERE created_by = p_user_id 
    AND status = 'active'
    AND expires_at > NOW();
    
    IF v_active_codes >= v_ambassador.max_codes THEN
        RETURN json_build_object(
            'success', false,
            'error', 'max_codes_reached'
        );
    END IF;
    
    -- Generate unique 8-character code
    LOOP
        v_new_code := UPPER(SUBSTRING(MD5(RANDOM()::TEXT || NOW()::TEXT) FROM 1 FOR 8));
        EXIT WHEN NOT EXISTS (SELECT 1 FROM referral_codes WHERE code = v_new_code);
    END LOOP;
    
    -- Insert new code (expires in 30 days, gives 7 days premium)
    INSERT INTO referral_codes (code, created_by, premium_days, expires_at)
    VALUES (v_new_code, p_user_id, 7, NOW() + INTERVAL '30 days')
    RETURNING * INTO v_code_record;
    
    RETURN json_build_object(
        'success', true,
        'code', v_new_code,
        'expires_at', v_code_record.expires_at,
        'premium_days', v_code_record.premium_days
    );
END;
$$;

-- ============================================
-- 7. RPC: REDEEM REFERRAL CODE
-- ============================================

CREATE OR REPLACE FUNCTION redeem_referral_code(p_user_id UUID, p_code TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_user users%ROWTYPE;
    v_code_record referral_codes%ROWTYPE;
    v_new_expiry TIMESTAMPTZ;
    v_ambassador_name TEXT;
BEGIN
    -- Get user record
    SELECT * INTO v_user FROM users WHERE id = p_user_id;
    
    IF NOT FOUND THEN
        RETURN json_build_object(
            'success', false,
            'error', 'user_not_found'
        );
    END IF;
    
    -- Check if user has already used a referral code (one-time only)
    IF v_user.has_used_referral THEN
        RETURN json_build_object(
            'success', false,
            'error', 'already_used_referral'
        );
    END IF;
    
    -- Get code record
    SELECT * INTO v_code_record
    FROM referral_codes
    WHERE code = UPPER(TRIM(p_code));
    
    IF NOT FOUND THEN
        RETURN json_build_object(
            'success', false,
            'error', 'invalid_code'
        );
    END IF;
    
    -- Check code status
    IF v_code_record.status = 'redeemed' THEN
        RETURN json_build_object(
            'success', false,
            'error', 'code_already_redeemed'
        );
    END IF;
    
    IF v_code_record.status = 'revoked' THEN
        RETURN json_build_object(
            'success', false,
            'error', 'code_revoked'
        );
    END IF;
    
    IF v_code_record.expires_at < NOW() THEN
        -- Mark as expired
        UPDATE referral_codes SET status = 'expired' WHERE id = v_code_record.id;
        RETURN json_build_object(
            'success', false,
            'error', 'code_expired'
        );
    END IF;
    
    -- Prevent self-redemption
    IF v_code_record.created_by = p_user_id THEN
        RETURN json_build_object(
            'success', false,
            'error', 'cannot_redeem_own_code'
        );
    END IF;
    
    -- Calculate new premium expiry
    IF v_user.premium_expires_at IS NOT NULL AND v_user.premium_expires_at > NOW() THEN
        -- Extend existing premium
        v_new_expiry := v_user.premium_expires_at + (v_code_record.premium_days || ' days')::INTERVAL;
    ELSE
        -- New premium activation
        v_new_expiry := NOW() + (v_code_record.premium_days || ' days')::INTERVAL;
    END IF;
    
    -- Update user's premium status
    UPDATE users 
    SET premium_expires_at = v_new_expiry,
        has_used_referral = TRUE,
        referred_by = v_code_record.created_by
    WHERE id = p_user_id;
    
    -- Mark code as redeemed
    UPDATE referral_codes 
    SET status = 'redeemed',
        redeemed_by = p_user_id,
        redeemed_at = NOW()
    WHERE id = v_code_record.id;
    
    -- Record transaction
    INSERT INTO premium_transactions (
        user_id, transaction_type, source_code, source_user_id, 
        premium_days, expires_at
    ) VALUES (
        p_user_id, 'referral', v_code_record.code, v_code_record.created_by,
        v_code_record.premium_days, v_new_expiry
    );
    
    -- Get ambassador name for welcome message
    SELECT COALESCE(display_name, username) INTO v_ambassador_name
    FROM users WHERE id = v_code_record.created_by;
    
    RETURN json_build_object(
        'success', true,
        'premium_days', v_code_record.premium_days,
        'expires_at', v_new_expiry,
        'referred_by_name', v_ambassador_name
    );
END;
$$;

-- ============================================
-- 8. RPC: GET AMBASSADOR CODES
-- ============================================

CREATE OR REPLACE FUNCTION get_ambassador_codes(p_user_id UUID)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_codes JSON;
BEGIN
    SELECT json_agg(
        json_build_object(
            'id', rc.id,
            'code', rc.code,
            'status', CASE 
                WHEN rc.status = 'active' AND rc.expires_at < NOW() THEN 'expired'
                ELSE rc.status
            END,
            'premium_days', rc.premium_days,
            'created_at', rc.created_at,
            'expires_at', rc.expires_at,
            'redeemed_at', rc.redeemed_at,
            'redeemed_by_name', COALESCE(u.display_name, u.username)
        )
        ORDER BY rc.created_at DESC
    ) INTO v_codes
    FROM referral_codes rc
    LEFT JOIN users u ON rc.redeemed_by = u.id
    WHERE rc.created_by = p_user_id;
    
    RETURN COALESCE(v_codes, '[]'::JSON);
END;
$$;

-- ============================================
-- 9. RPC: GET PREMIUM USER COUNT
-- ============================================

CREATE OR REPLACE FUNCTION get_premium_user_count()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM users
    WHERE premium_expires_at > NOW();
    
    RETURN v_count;
END;
$$;

-- ============================================
-- 10. RPC: VALIDATE PREMIUM STATUS
-- ============================================
-- Server-side source of truth for premium status

CREATE OR REPLACE FUNCTION validate_premium_status(p_user_id UUID)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_user users%ROWTYPE;
    v_is_ambassador BOOLEAN;
BEGIN
    SELECT * INTO v_user FROM users WHERE id = p_user_id;
    
    IF NOT FOUND THEN
        RETURN json_build_object(
            'is_premium', false,
            'error', 'user_not_found'
        );
    END IF;
    
    -- Check if user is an active ambassador (free premium)
    SELECT EXISTS (
        SELECT 1 FROM ambassadors 
        WHERE user_id = p_user_id AND status = 'active'
    ) INTO v_is_ambassador;
    
    RETURN json_build_object(
        'is_premium', v_is_ambassador OR (v_user.premium_expires_at IS NOT NULL AND v_user.premium_expires_at > NOW()),
        'is_ambassador', v_is_ambassador,
        'expires_at', v_user.premium_expires_at,
        'selected_theme_id', v_user.selected_theme_id,
        'has_used_referral', COALESCE(v_user.has_used_referral, false)
    );
END;
$$;

-- ============================================
-- 11. TRIGGER: Auto-expire codes
-- ============================================

CREATE OR REPLACE FUNCTION auto_expire_referral_codes()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE referral_codes 
    SET status = 'expired' 
    WHERE status = 'active' AND expires_at < NOW();
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Run cleanup periodically (can be triggered by any insert/update to referral_codes)
DROP TRIGGER IF EXISTS trigger_auto_expire_codes ON referral_codes;
CREATE TRIGGER trigger_auto_expire_codes
    AFTER INSERT OR UPDATE ON referral_codes
    FOR EACH STATEMENT
    EXECUTE FUNCTION auto_expire_referral_codes();

-- ============================================
-- 12. RLS POLICIES
-- ============================================

ALTER TABLE ambassadors ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE premium_transactions ENABLE ROW LEVEL SECURITY;

-- Ambassadors: Users can view their own ambassador status
CREATE POLICY "Users can view own ambassador status" ON ambassadors
    FOR SELECT USING (auth.uid() = user_id);

-- Referral codes: Creators can view their codes, redeemers can view code they redeemed
CREATE POLICY "Users can view own referral codes" ON referral_codes
    FOR SELECT USING (auth.uid() = created_by OR auth.uid() = redeemed_by);

-- Premium transactions: Users can view their own transactions
CREATE POLICY "Users can view own transactions" ON premium_transactions
    FOR SELECT USING (auth.uid() = user_id);

-- Grant execute on functions
GRANT EXECUTE ON FUNCTION check_ambassador_status(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION generate_referral_code(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION redeem_referral_code(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION get_ambassador_codes(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION get_premium_user_count() TO authenticated;
GRANT EXECUTE ON FUNCTION validate_premium_status(UUID) TO authenticated;
